/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

/**
 *
 * @author APRENDIZ SENA
 */
public class admin extends javax.swing.JFrame {

    /** Creates new form admin */
    public admin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todo = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mostracl = new javax.swing.JMenuItem();
        vendedor = new javax.swing.JMenu();
        sale = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        producin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        SALIRADMIN = new javax.swing.JMenuItem();

        todo.setBackground(new java.awt.Color(204, 255, 255));
        todo.setAutoscrolls(true);
        todo.setDoubleBuffered(true);
        todo.setFocusTraversalPolicyProvider(true);
        todo.setInheritsPopupMenu(true);

        javax.swing.GroupLayout todoLayout = new javax.swing.GroupLayout(todo);
        todo.setLayout(todoLayout);
        todoLayout.setHorizontalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        todoLayout.setVerticalGroup(
            todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jMenuBar2.setBackground(new java.awt.Color(102, 102, 102));

        jMenu3.setForeground(new java.awt.Color(102, 255, 255));
        jMenu3.setText("CLIENTE");

        mostracl.setBackground(new java.awt.Color(0, 0, 0));
        mostracl.setForeground(new java.awt.Color(51, 51, 255));
        mostracl.setText("show");
        jMenu3.add(mostracl);

        jMenuBar2.add(jMenu3);

        vendedor.setForeground(new java.awt.Color(102, 255, 255));
        vendedor.setText("VENDEDOR");

        sale.setBackground(new java.awt.Color(0, 0, 0));
        sale.setForeground(new java.awt.Color(51, 255, 51));
        sale.setText("show");
        vendedor.add(sale);

        jMenuBar2.add(vendedor);

        jMenu1.setForeground(new java.awt.Color(102, 255, 255));
        jMenu1.setText("PRODUCTOS");

        producin.setBackground(new java.awt.Color(0, 0, 0));
        producin.setForeground(new java.awt.Color(204, 0, 204));
        producin.setText("show");
        jMenu1.add(producin);

        jMenuBar2.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(102, 255, 255));
        jMenu2.setText("EXIT");

        SALIRADMIN.setForeground(new java.awt.Color(255, 0, 0));
        SALIRADMIN.setText("SALIR");
        jMenu2.add(SALIRADMIN);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(todo, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(todo)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem SALIRADMIN;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem mostracl;
    public javax.swing.JMenuItem producin;
    public javax.swing.JMenuItem sale;
    public javax.swing.JDesktopPane todo;
    public javax.swing.JMenu vendedor;
    // End of variables declaration//GEN-END:variables

}
